version: '3.1'

services:

  main:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - COMMAND_OPTIONS=-master http://${JENKINS_IP}/jenkins -username ${MASTER_USER:-admin} -password ${MASTER_PASS:-admin} -labels 'docker' -executors 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    deploy:
      mode: global
