FROM golang:1.8

MAINTAINER 	Viktor Farcic <viktor@farcic.com>

RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common expect && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get -y install docker-ce

COPY . /src
WORKDIR /src
RUN chmod +x /src/run-tests.sh
RUN go get -d -v -t

CMD ["sh", "-c", "/src/run-tests.sh"]