HTTP/1.0 500 Internal Server Error
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
  <body>
    <h3>Docker Flow: Proxy</h3>
    <h1>500 Internal Server Error</h1>
    No server is available to handle this request.
  </body>
</html>