version: "3.2"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
    - 80:80
    - 443:443
    networks:
    - default
    environment:
    - DFP_SERVICE_SERVICE_NAME=proxy_main
    - DFP_SERVICE_SERVICE_PATH=/demoxxx
    - DFP_SERVICE_REQ_PATH_SEARCH_REPLACE=/demoxxx,/demo
    - DFP_SERVICE_OUTBOUND_HOSTNAME=blog
    - DFP_SERVICE_PORT=8080

  main:
    image: ${DOCKER_HUB_USER:-vfarcic}/go-demo-2:${TAG:-latest}
    environment:
      - DB=db
    networks:
      - default
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.servicePath=/demo
        - com.df.port=8080

  db:
    image: mongo
    networks:
      - default

networks:
  default:
    external: false
